// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAxQ3uYmgacxV5sFoxqpH1GgczVxNI-kM',
    appId: '1:102032456378:web:5446aab2d1210300376083',
    messagingSenderId: '102032456378',
    projectId: 'flutter-proj-79b6a',
    authDomain: 'flutter-proj-79b6a.firebaseapp.com',
    storageBucket: 'flutter-proj-79b6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB12BW6vjWQxAkBsKvOpC_vOK--w2HIEYc',
    appId: '1:102032456378:android:c486ec577397aa4f376083',
    messagingSenderId: '102032456378',
    projectId: 'flutter-proj-79b6a',
    storageBucket: 'flutter-proj-79b6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Ko8eQD0UfdijxYtoXN1LihO7lavp2R0',
    appId: '1:102032456378:ios:3ab90621f7399633376083',
    messagingSenderId: '102032456378',
    projectId: 'flutter-proj-79b6a',
    storageBucket: 'flutter-proj-79b6a.firebasestorage.app',
    iosBundleId: 'com.example.flutter05Instagram',
  );
}
